### ISSUE TITLE
Detect if c-autodoc is parsing the file?

### ISSUE THREAD

**Issue by polwel** [speedyleion/sphinx-c-autodoc#15]
Is there any way to detect if the source file is currently processed by the documentation generator, rather than being built properly?

I imagine there could be a macro that is only defined by *sphinx-c-autodoc*, so that I can do

```C
#ifdef SPHINX_C_AUTODOC
// whatever
#endif
```

**Comment by speedyleion** [comment]
At this time not built in.  There is support for  compile_commands.json, but I imagine most won't want a special one just for docs and I've noticed the heuristic to apply to headers can be a bit iffy for c code.

It seems like the define would be unique enough to not likely collide.  It could also be a  pre flag so someone could come back and undefine in the compile commands.json if they're using it.

Curious what the use case is, I would think it might be more likely to want to exclude an area rather than include for docs.

**Comment by speedyleion** [comment]
I ended up adding a configuration value ``c_autodoc_compilation_args``.
I think this will be more robust and easier to leverage for other uses.  So one can simply add
```
c_autodoc_compilation_args = ["-DSPHINX_C_AUTODOC"]
```
to their conf.py if they want the initial requested behaviour.

**Comment by polwel** [comment]
That is perfect, even better than my original suggestion. Very nice of you to deal with this so quickly.

Sorry I missed your original reply. You asked for more info on the usecase. What I wanted to do was mocking some function attributes, that worked fine with gcc, but that clang would choke on. I ended up having a `#ifdef` switch that differentiates clang vs gcc. In case of clang it voids the attribute macro. Not a great solution, but it worked.
